name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [synchronize, opened]

jobs:
  test-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --framework net48 ./src/LibSVMsharp.Tests/LibSVMsharp.Tests.csproj
      
    - name: Test
      run: dotnet test --no-build --framework net48 --verbosity normal

  test-linux:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
            
    - name: Restore dependencies
      run: dotnet restore
          
    - name: Build
      run: dotnet build --no-restore --framework net8 ./src/LibSVMsharp.Tests/LibSVMsharp.Tests.csproj
          
    - name: Test
      run: dotnet test --no-build --framework net8 --verbosity normal
    